export const types = {
  GET_EXPENSES: "GET_EXPENSES",
  DELETE_EXPENSE: "DELETE_EXPENSE",
  TOGGLE_ADD_EXPENSE: "TOGGLE_ADD_EXPENSE",
  ADD_EXPENSE: "ADD_EXPENSE",
  SELECTED_EXPENSE_TO_DELETE: "SELECTED_EXPENSE_TO_DELETE",
};
